MWAAAAAAAAAAAAA  M : Mac
AWWAAAAWAAAAAAA  A : free, W : wall
AAWWAAWWAAAAAAA
AAAWWWWAAAAAAAA
AAAAWAAAAAAAAAA
AAAAAAAAAAAAAAA
AAAWAAAAAAAAAAA
AAAAAAAAAAAAAAA
AAAAAAAAAAAAAAA
AAAAAAAAAAAAAAA
WWWWAAAAAAAAAAA
AAAAAWWWAAAAAAA
AAAAAWAWWAAWAWW
AAAAAWAAAAAWAGS  G : guardian, S : stairs
AAAAAWAAAAAWWWW
KOKOKOKOKOO